# Generated by Django 5.0.1 on 2024-01-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
